-- MINIX PUSH NOTIFICATION DATABASE SETUP
-- Run this complete section once in Supabase SQL Editor.

create table if not exists public.minix_push_subscriptions (
  id bigint generated by default as identity primary key,
  username text not null,
  role text,
  endpoint text not null unique,
  subscription jsonb not null,
  device_label text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.minix_notification_log (
  id bigint generated by default as identity primary key,
  username text not null,
  role text,
  report_date date,
  notification_type text not null default 'DAILY_REPORT',
  status text not null,
  error_message text,
  sent_at timestamptz not null default now()
);

alter table public.minix_push_subscriptions enable row level security;
alter table public.minix_notification_log enable row level security;

create or replace function public.minix_is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles p where lower(p.username)=lower(auth.jwt()->>'email') and lower(p.role) in ('admin','manager') and p.is_active=true) $$;

create or replace function public.minix_save_push_subscription(p_username text,p_role text,p_subscription jsonb,p_device_label text default null)
returns void language plpgsql security definer set search_path=public
as $$
declare ep text;
begin
  ep:=p_subscription->>'endpoint';
  if ep is null or length(ep)<20 then raise exception 'Invalid push subscription'; end if;
  if not exists(
    select 1 from public.minix_users u
    where lower(trim(u.username))=lower(trim(p_username))
      and coalesce(u.active,true)=true
  ) then
    raise exception 'Active MINIX user not found';
  end if;
  insert into public.minix_push_subscriptions(username,role,endpoint,subscription,device_label,active,last_seen_at,updated_at)
  values(lower(trim(p_username)),p_role,ep,p_subscription,p_device_label,true,now(),now())
  on conflict(endpoint) do update set username=excluded.username,role=excluded.role,subscription=excluded.subscription,device_label=excluded.device_label,active=true,last_seen_at=now(),updated_at=now();
end;
$$;

revoke all on function public.minix_save_push_subscription(text,text,jsonb,text) from public;
grant execute on function public.minix_save_push_subscription(text,text,jsonb,text) to anon,authenticated;

drop policy if exists "Admins manage push subscriptions" on public.minix_push_subscriptions;
drop policy if exists "Admins view notification log" on public.minix_notification_log;
create policy "Admins manage push subscriptions" on public.minix_push_subscriptions for all to authenticated using(public.minix_is_admin()) with check(public.minix_is_admin());
create policy "Admins view notification log" on public.minix_notification_log for select to authenticated using(public.minix_is_admin());

grant select,update on public.minix_push_subscriptions to authenticated;
grant select on public.minix_notification_log to authenticated;

-- AFTER deploying the send-daily-reports Edge Function, create three Cron jobs
-- in Supabase Dashboard > Integrations > Cron using these UTC times:
-- 10:30 UTC = 4:00 PM IST, 10:45 UTC = 4:15 PM IST, 11:00 UTC = 4:30 PM IST.
-- Each job should POST {"mode":"scheduled"} to the Edge Function and include
-- header x-cron-secret matching the PUSH_CRON_SECRET Edge Function secret.
