-- Run this complete file once in Supabase > SQL Editor.

create table if not exists public.minix_daily_trader_reports (
  id bigint generated by default as identity primary key,
  report_date date not null,
  trader_name text not null,
  today_status text not null default 'NO_TRADE'
    check (today_status in ('TRADED','NO_TRADE','SICK_LEAVE','ON_LEAVE')),
  fno_total_fund numeric not null default 0,
  cash_total_fund numeric not null default 0,
  mcx_total_fund numeric not null default 0,
  total_margin numeric not null default 0,
  margin_utilized numeric not null default 0,
  fno_gross numeric not null default 0,
  fno_charges numeric not null default 0,
  cash_gross numeric not null default 0,
  cash_charges numeric not null default 0,
  mcx_gross numeric not null default 0,
  mcx_charges numeric not null default 0,
  reason text not null default '',
  submitted_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint minix_daily_trader_reports_day_user_unique
    unique (report_date, trader_name)
);

-- Safe upgrade for users who already ran the previous SQL version.
alter table public.minix_daily_trader_reports
  add column if not exists fno_total_fund numeric not null default 0,
  add column if not exists cash_total_fund numeric not null default 0,
  add column if not exists mcx_total_fund numeric not null default 0;

alter table public.minix_daily_trader_reports enable row level security;

drop policy if exists "minix_daily_reports_read" on public.minix_daily_trader_reports;
create policy "minix_daily_reports_read"
on public.minix_daily_trader_reports
for select
to anon, authenticated
using (true);

drop policy if exists "minix_daily_reports_insert" on public.minix_daily_trader_reports;
create policy "minix_daily_reports_insert"
on public.minix_daily_trader_reports
for insert
to anon, authenticated
with check (true);

drop policy if exists "minix_daily_reports_update" on public.minix_daily_trader_reports;
create policy "minix_daily_reports_update"
on public.minix_daily_trader_reports
for update
to anon, authenticated
using (true)
with check (true);

grant select, insert, update on public.minix_daily_trader_reports to anon, authenticated;
grant usage, select on sequence public.minix_daily_trader_reports_id_seq to anon, authenticated;

notify pgrst, 'reload schema';
