-- Run this once in Supabase -> SQL Editor.
-- It keeps an automatic audit trail whenever a trader edits an existing daily report.

create table if not exists public.minix_daily_report_edits (
  id bigint generated by default as identity primary key,
  report_id text,
  report_date date not null,
  trader_name text not null,
  old_data jsonb not null,
  new_data jsonb not null,
  edited_by text,
  edited_at timestamptz not null default now()
);

create index if not exists minix_daily_report_edits_date_name_idx
  on public.minix_daily_report_edits (report_date desc, trader_name);

alter table public.minix_daily_report_edits enable row level security;

drop policy if exists "Dashboard can read daily report edits"
  on public.minix_daily_report_edits;

create policy "Dashboard can read daily report edits"
  on public.minix_daily_report_edits
  for select
  to anon, authenticated
  using (true);

grant select on public.minix_daily_report_edits to anon, authenticated;

create or replace function public.minix_log_daily_report_edit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if to_jsonb(old) is distinct from to_jsonb(new) then
    insert into public.minix_daily_report_edits
      (report_id, report_date, trader_name, old_data, new_data, edited_by, edited_at)
    values
      (new.id::text, new.report_date, new.trader_name, to_jsonb(old), to_jsonb(new),
       coalesce(new.submitted_by, new.trader_name), now());
  end if;
  return new;
end;
$$;

drop trigger if exists minix_daily_report_edit_audit
  on public.minix_daily_trader_reports;

create trigger minix_daily_report_edit_audit
after update on public.minix_daily_trader_reports
for each row
execute function public.minix_log_daily_report_edit();

notify pgrst, 'reload schema';
